import { AppData } from "@/components/AppCard";

export type { AppData };

export const apps: AppData[] = [
  {
    name: "Everyday Import",
    slug: "everyday-import",
    description: "Import CSV & Excel files to monday boards with smart column mapping, error handling, and batch processing.",
    longDescription: "Everyday Import is the ultimate solution for bringing your external data into monday.com. Whether you're migrating from another platform, importing client lists, or syncing inventory data, our smart column mapping and batch processing makes it effortless. Built with enterprise-grade security and running directly on monday.com servers.",
    features: [
      "Smart column mapping with auto-detection",
      "Support for CSV, XLSX, and XLS files",
      "Batch processing for large datasets",
      "Error handling with detailed reports",
      "Status and dropdown value matching",
      "Duplicate detection and handling",
      "Progress tracking with real-time updates",
      "Runs on monday.com servers (SOC 2 compliant)",
    ],
    status: "live",
    marketplaceUrl: "https://monday.com/marketplace/listing/10000148/everyday-import",
    icon: "import",
  },
  {
    name: "Everyday Export",
    slug: "everyday-export",
    description: "Export monday boards to CSV, Excel, PDF, and more formats with custom templates.",
    longDescription: "Everyday Export gives you full control over how you export your monday.com data. Create custom templates, schedule automated exports, and generate professional PDF reports. Perfect for sharing data with external stakeholders or creating backups.",
    features: [
      "Export to CSV, Excel, and PDF",
      "Custom export templates",
      "Scheduled automated exports",
      "Filter and select specific columns",
      "Include subitems and linked boards",
      "Professional PDF report generation",
      "Email delivery of exports",
      "Bulk export multiple boards",
    ],
    status: "coming-soon",
    icon: "export",
  },
  {
    name: "Everyday Form",
    slug: "everyday-form",
    description: "Create beautiful, customizable forms that feed directly into your monday boards.",
    longDescription: "Everyday Form lets you create stunning, branded forms that capture data directly into your monday.com boards. Perfect for lead capture, customer feedback, event registrations, and internal requests. No coding required - just drag, drop, and publish.",
    features: [
      "Drag-and-drop form builder",
      "Custom branding and themes",
      "Conditional logic and branching",
      "File upload support",
      "Email notifications",
      "Form analytics and tracking",
      "Embeddable on any website",
      "Mobile-responsive design",
    ],
    status: "coming-soon",
    icon: "form",
  },
  {
    name: "Everyday Sync",
    slug: "everyday-sync",
    description: "Two-way sync between monday.com and Google Sheets, Excel Online, and Airtable.",
    longDescription: "Everyday Sync keeps your monday.com boards in perfect harmony with your spreadsheets. Set up real-time two-way sync with Google Sheets, Excel Online, or Airtable. Changes flow automatically in both directions, ensuring your data is always consistent across platforms.",
    features: [
      "Real-time two-way sync",
      "Google Sheets integration",
      "Excel Online support",
      "Airtable sync",
      "Custom field mapping",
      "Conflict resolution rules",
      "Sync scheduling options",
      "Detailed sync logs",
    ],
    status: "coming-soon",
    icon: "connect",
  },
  {
    name: "Everyday Mail",
    slug: "everyday-mail",
    description: "Email automation for monday.com - send templated emails based on board triggers.",
    longDescription: "Everyday Mail connects your monday.com workflows to powerful email automation. Send personalized emails when items change status, due dates approach, or custom triggers fire. Use dynamic templates with board data to create professional, automated communications.",
    features: [
      "Trigger-based email automation",
      "Dynamic email templates",
      "Personalization with board data",
      "Schedule emails for specific times",
      "Track opens and clicks",
      "Attachment support",
      "Multiple email providers",
      "Email sequence automations",
    ],
    status: "coming-soon",
    icon: "mail",
  },
  {
    name: "Everyday Signature",
    slug: "everyday-signature",
    description: "E-signature integration - collect legally binding signatures from your monday boards.",
    longDescription: "Everyday Signature brings legally binding e-signatures directly into your monday.com workflow. Generate documents from templates, send for signature, and track status - all without leaving monday. Perfect for contracts, approvals, and compliance documentation.",
    features: [
      "Legally binding e-signatures",
      "Document templates with placeholders",
      "Multi-party signing workflows",
      "Automatic status updates in monday",
      "Audit trail and compliance",
      "Reminder notifications",
      "Signed document storage",
      "Integration with popular e-sign providers",
    ],
    status: "coming-soon",
    icon: "signature",
  },
  {
    name: "Everyday Dashboard",
    slug: "everyday-dashboard",
    description: "Custom dashboards with advanced charts, KPIs, and real-time metrics for your monday boards.",
    longDescription: "Everyday Dashboard transforms your monday.com data into powerful visual insights. Create custom dashboards with advanced charts, KPIs, and real-time metrics that go beyond monday's native widgets. Perfect for executives, team leads, and stakeholders who need at-a-glance visibility.",
    features: [
      "Advanced chart types (Gantt, Sankey, Heatmaps)",
      "Custom KPI widgets with targets",
      "Real-time data refresh",
      "Cross-board data aggregation",
      "Drill-down capabilities",
      "Shareable dashboard links",
      "Scheduled email reports",
      "Mobile-optimized views",
    ],
    status: "coming-soon",
    icon: "dashboard",
  },
  {
    name: "Everyday Calendar",
    slug: "everyday-calendar",
    description: "Advanced calendar view with resource scheduling, availability tracking, and team coordination.",
    longDescription: "Everyday Calendar brings powerful scheduling capabilities to monday.com. View items across multiple boards in a unified calendar, manage resource availability, prevent double-booking, and coordinate team schedules effortlessly. Sync with Google Calendar and Outlook.",
    features: [
      "Multi-board calendar view",
      "Resource scheduling and availability",
      "Drag-and-drop rescheduling",
      "Google Calendar sync",
      "Outlook integration",
      "Team availability overlay",
      "Conflict detection",
      "Recurring events support",
    ],
    status: "coming-soon",
    icon: "calendar",
  },
  {
    name: "Everyday Timesheet",
    slug: "everyday-timesheet",
    description: "Time tracking with approval workflows, reporting, and seamless monday board integration.",
    longDescription: "Everyday Timesheet makes time tracking effortless within monday.com. Track time against items, submit timesheets for approval, and generate detailed reports for billing and payroll. Perfect for agencies, consultants, and teams who need accurate time tracking.",
    features: [
      "One-click time tracking",
      "Timer and manual entry",
      "Approval workflows",
      "Billable vs non-billable hours",
      "Client and project reports",
      "Weekly timesheet views",
      "Export for payroll",
      "Budget tracking and alerts",
    ],
    status: "coming-soon",
    icon: "timesheet",
  },
  {
    name: "Everyday Connect",
    slug: "everyday-connect",
    description: "Connect monday.com with your favorite tools - HubSpot, QuickBooks, Salesforce, and more.",
    longDescription: "Everyday Connect bridges monday.com with the tools your team already uses. Set up powerful two-way syncs with CRMs, accounting software, marketing platforms, and more. No coding required - just authenticate, map your fields, and let the data flow automatically.",
    features: [
      "HubSpot, Salesforce, Pipedrive sync",
      "QuickBooks and Xero integration",
      "Google Sheets two-way sync",
      "Mailchimp and ActiveCampaign",
      "Custom field mapping",
      "Real-time or scheduled sync",
      "Conflict resolution rules",
      "Sync history and logs",
    ],
    status: "coming-soon",
    icon: "connect",
  },
  {
    name: "Everyday Marketing",
    slug: "everyday-marketing",
    description: "Marketing campaign management with analytics, A/B testing, and multi-channel tracking.",
    longDescription: "Everyday Marketing transforms monday.com into a powerful marketing command center. Plan campaigns, track performance across channels, run A/B tests, and measure ROI - all from your monday boards. Perfect for marketing teams who want to keep everything in one place.",
    features: [
      "Campaign planning and scheduling",
      "Multi-channel performance tracking",
      "A/B testing workflows",
      "UTM link generator and tracker",
      "Marketing calendar view",
      "ROI and attribution reporting",
      "Social media post scheduling",
      "Budget tracking and spend analysis",
    ],
    status: "coming-soon",
    icon: "marketing",
  },
  {
    name: "Everyday Inventory",
    slug: "everyday-inventory",
    description: "Inventory management with stock tracking, alerts, barcode scanning, and reorder automation.",
    longDescription: "Everyday Inventory turns monday.com into a complete inventory management system. Track stock levels in real-time, get low-stock alerts, scan barcodes, and automate reorders. Perfect for warehouses, retail, e-commerce, and any team managing physical products.",
    features: [
      "Real-time stock level tracking",
      "Low stock alerts and notifications",
      "Barcode and QR code scanning",
      "Automated reorder triggers",
      "Multi-location inventory",
      "Stock movement history",
      "Inventory valuation reports",
      "Supplier management integration",
    ],
    status: "coming-soon",
    icon: "inventory",
  },
  {
    name: "Everyday Security",
    slug: "everyday-security",
    description: "Advanced security controls, audit logs, and compliance monitoring for your monday.com workspace.",
    longDescription: "Everyday Security adds enterprise-grade security features to your monday.com workspace. Monitor user activity, enforce access controls, track sensitive data, and generate compliance reports. Essential for teams handling confidential information.",
    features: [
      "Detailed audit logs and activity tracking",
      "Role-based access controls",
      "Sensitive data detection and alerts",
      "User session monitoring",
      "Compliance reports (SOC 2, GDPR, HIPAA)",
      "Two-factor authentication enforcement",
      "Data export restrictions",
      "Security incident alerts",
    ],
    status: "coming-soon",
    icon: "security",
  },
  {
    name: "Everyday Backup",
    slug: "everyday-backup",
    description: "Automated backups, version history, and disaster recovery for your monday.com boards.",
    longDescription: "Everyday Backup ensures your monday.com data is always safe and recoverable. Schedule automatic backups, browse version history, and restore boards to any point in time. Never lose critical work data again.",
    features: [
      "Automated scheduled backups",
      "Point-in-time recovery",
      "Version history browsing",
      "Cross-board backup policies",
      "One-click restore",
      "Backup encryption at rest",
      "Retention policy management",
      "Backup status notifications",
    ],
    status: "coming-soon",
    icon: "backup",
  },
  {
    name: "Request an App",
    slug: "request-app",
    description: "Have an app idea? Share it with us and earn $100 if we build it.",
    longDescription: "Have a specific workflow or integration in mind? We're always looking for new app ideas from the monday.com community. Share your requirements and if we build your app, you'll earn $100 once it generates revenue.",
    features: [
      "Share your app idea",
      "$100 one-time commission",
      "No development required",
      "Priority for popular requests",
      "Early access to new apps",
      "Direct communication with our team",
      "Community voting on features",
      "Partnership opportunities",
    ],
    status: "coming-soon",
    icon: "request",
  },
];

export const liveApps = apps.filter((app) => app.status === "live");
export const comingSoonApps = apps.filter((app) => app.status === "coming-soon");
